### ISSUE TITLE
About partial ROM flashing

### ISSUE THREAD

**Issue by Lar-Sen** [sq5bpf/k5prog#16]
Not an issue, just a modding proposal :)
Inspired by the ideas you had when developing k5prog, I initially thought that genuine bootloader would accept partial ROM flashing, but as you know, it doesn't.
They decided to wipe the entire user ROM region as soon as a correct payload adressed to offset 0 is received, rendering your work about select block flashing useless.
After a bit of tinkering I modded my bootloader to accept partial flashing. If ever interested , it is there https://github.com/Lar-Sen/Quansheng_UV-K5_Kitchen/tree/main/Bootloader_mods

**Comment by sq5bpf** [comment]
i already implemented this, but deleted it, because  i didn't know that all flash is deleted upon touching block 0.

For now i focus on my tools working with the official firmware and official bootloader, so i will not support this. But i may have to rethink this, because it seems the UV-K5 is getting more attention with modified firmware than with official vendor firmware.
