### ISSUE TITLE
can be used for save calibration files of radio?

### ISSUE THREAD

**Issue by iw2evk** [sq5bpf/k5prog#26]
Hi,

this program can be used under linux ubuntu for download the calibration files of radio?

Thanks

Roberto iw2evk

Milan

**Comment by maxlinux2000** [comment]
+1

**Comment by sq5bpf** [comment]
I've programmed both k5prog and the chirp driver to download everything, including calibration data.

k5prog and chirp will download all of the eeprom. The calibration data is in addresses 0x1d00 - 0x1fff.

So to download calibration data just use (it is recommended in the README that you do this):
k5prog -r -f uvk5_eeprom.raw
or take the config file downloaded via chirp (in this example the file is called config_uvk5.img) and take the first 8192 bytes:
dd if=config_uvk5.img of=uv5k_eeprom.raw bs=8192 count=1


To program the uv5k_eeprom.raw  back into the radio:
k5prog -f uv5k_eeprom.raw -B -YYY

Maybe i should put this into the README, because many people are breaking their radio's calibration by using what they have read on the internet without thinking first.

**Comment by iw2evk** [comment]
hi,

i suggest to add  this to readme file for explain how to download and how to try to unbreaking a radio.
tnk for this reply
73
Roberto

**Comment by maxlinux2000** [comment]
Hi.
One of my friends sent me his calibration file to compare it to what I get with k5prog.
My friend uses k5prog-win.

The problem is that I get a file of 8192 bytes, but my friend has a file of only 512bytes.
The size of 512bytes has been confirmed by the IJV-mod developper.

so I don't understand how to use k5prog to get only the 512Bytes calibration file.

I have also seen that k5prog cannot send this calibration file to my sacrificial k5 because it says it is too small and does not have the correct CRC.

And this is why I am a bit dizzy :-)
![Captura desde 2024-04-01 22-39-18](https://github.com/sq5bpf/k5prog/assets/5683921/2a57bd2b-f958-4d9a-a952-51861f8c2f97)

**Comment by qrp73** [comment]
> The problem is that I get a file of 8192 bytes, but my friend has a file of only 512bytes. The size of 512bytes has been confirmed by the IJV-mod developper.
> 
> so I don't understand how to use k5prog to get only the 512Bytes calibration file.

The calibration data is the last 512 bytes of a full eeprom content file.
In order to compare them, you're needs to convert files to a text hex file.

For example, if you have k5_eeprom.raw file, then:
```
xxd -c 16 -g 1 k5_eeprom.raw k5_eeprom.hex
```
hex file is a text file which contains data in hex format.

Then you can compare two hex files with meld:
```
meld k5_eeprom.hex other_file.hex
```

If you do that for your case, just ignore data at the beginning of file which is present in your file and missing in file from your friend.

**Comment by iw2evk** [comment]
Hi, seem this fork have a modification for write obfuscated data and standard data 

https://github.com/nica-f/k5prog

can you merge in standard version ?

P.s. seem can save squelch calibration e nbattery calibration data in raw files .
