### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by OneOfEleven** [sq5bpf/k5prog#8]
Hi Jacek

I've made a little windows GUI version using your comm routines, hope that's OK ?

https://github.com/OneOfEleven/k5prog-win/tree/main

Such is windows monkeys life ;)

**Comment by sq5bpf** [comment]
Of course it's ok :)
Don't use windows so can't check it, but congratulations ;)

**Comment by ephestione** [comment]
@OneOfEleven can you please disclose the equivalent k5prog options to your windows version features?
Which linux commandlines would one need to use for each feature of k5prog-win:

- flash firmware
- read config
- write config
- read calibration
- write calibration

I cannot find univocal mappings in the CLI help, nor I can find any other way of contacting you on your profile/repos.

**Comment by sq5bpf** [comment]
@OneOfEleven wrote his software based on mine, but i'm not sure why you want him to answer questions about my software. Of course he's welcome to do this, as is anyone else.

Please read the README file, however many times it's needed. It has all the help you need.

**Comment by ephestione** [comment]
> @OneOfEleven wrote his software based on mine, but i'm not sure why you want him to answer questions about my software. Of course he's welcome to do this, as is anyone else.
> 
> Please read the README file, however many times it's needed. It has all the help you need.

Thank you for the reply and I'm sorry if that came out as overstepping your obvious knowledge of your own software :sweat_smile: 
I asked the author of the port because the windows version, which I felt compelled to go back to after having moved to linux, by booting my laptop from my second ssd in order to made other changes to the radio, has a clear distinction between calibration read/write, confg read/write, and firmware write, which is not as clear in the commandline help options, and I guessed he would clarify the corresponding commandline parameters tied to each of the above gui buttons.
I did check your readme more than once, and while I made some educated guesses on the cli equivalent to those windows gui buttons, the warning about "I _think_ that the radio has calibration data above this address", and "the radioflash can potentially
brick your radio" didn't quite instill confidence in just trying the options out and see what happened, so I decided that simply reproducing what @OneOfEleven did with the original software was a safer option, hence I asked him what is the cli mapping of those buttons :smile:
